<#
.SYNOPSIS
    Consolidate Phase 1 discovery reports into a single markdown audit report
    with findings prioritized by severity.
.PARAMETER ReportsDir
    Path to reports directory. Defaults to ../../reports.
#>
[CmdletBinding()] param([string]$ReportsDir)
$ErrorActionPreference = "Stop"
Import-Module (Join-Path $PSScriptRoot ".." ".." "modules" "HTT.CrossTenant.Core.psm1") -Force
if (-not $ReportsDir) { $ReportsDir = Join-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) "reports" }

Write-HTTSection "Building Consolidated Audit Report"
$types = @("CrossTenantPolicyAudit","GuestUserInventory","SyncJobAudit","ConditionalAccessAudit","TeamsFederationAudit","IdentityGovernanceAudit")
$allFindings = @(); $reportData = @{}

foreach ($type in $types) {
    $f = Get-ChildItem -Path $ReportsDir -Filter "${type}_*.json" -EA SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($f) {
        Write-HTTFinding -Severity OK -Message "Found: $($f.Name)"
        $data = Get-Content $f.FullName -Raw | ConvertFrom-Json; $reportData[$type] = $data
        foreach ($prop in $data.PSObject.Properties) {
            $td = $prop.Value; if ($td.Findings) {
                foreach ($fi in $td.Findings) { $allFindings += [PSCustomObject]@{Tenant=$td.TenantAlias ?? $prop.Name; Severity=$fi.Severity; Domain=$fi.Domain ?? $type; Detail=$fi.Detail} }
            }
        }
    } else { Write-HTTFinding -Severity INFO -Message "No report for $type" }
}

$path = New-HTTReportPath -ReportName "ConsolidatedAuditReport" -Format "md"
$ts = Get-Date -Format "MMMM d, yyyy 'at' h:mm tt"
$md = "# HTT Brands — Cross-Tenant Identity Audit Report`n`n**Generated:** $ts`n**Tenants:** HTT (Hub), BCC, FN, TLL, DCE`n`n---`n`n## Summary`n`n"
$md += "| Severity | Count |`n|---|---|`n"
foreach ($s in @("CRITICAL","HIGH","MEDIUM","LOW","INFO")) { $md += "| $s | $(@($allFindings | Where-Object { $_.Severity -eq $s }).Count) |`n" }
$md += "`n---`n`n## Critical & High Findings`n`n"
$ch = $allFindings | Where-Object { $_.Severity -in @("CRITICAL","HIGH") } | Sort-Object Severity
if ($ch) { foreach ($f in $ch) { $icon = if($f.Severity -eq "CRITICAL"){"!!"}else{"!"}; $md += "- **[$($f.Severity)]** [$($f.Tenant)] $($f.Detail)`n" } }
else { $md += "*No critical or high findings.*`n" }
$md += "`n---`n`n## By Tenant`n"
foreach ($g in ($allFindings | Group-Object Tenant | Sort-Object Name)) {
    $md += "`n### $($g.Name)`n`n"
    foreach ($f in $g.Group) { $md += "- **$($f.Severity)** — $($f.Detail)`n" }
}
$md += "`n---`n*Generated by HTT Brands Cross-Tenant Utility*`n"
$md | Out-File $path -Encoding utf8
Write-Host "  Report: $path" -ForegroundColor Green

$csvPath = New-HTTReportPath -ReportName "AllFindings" -Format "csv"
$allFindings | Export-Csv -Path $csvPath -NoTypeInformation -Encoding utf8
Write-Host "  Findings CSV: $csvPath`n" -ForegroundColor Green
