import { useState, useEffect } from 'react';
import { NAV_ITEMS, METRICS } from './architecture/data';
import HubSpokeDiagram from './architecture/HubSpokeDiagram';
import PhaseTracker from './architecture/PhaseTracker';
import CompletedActions from './architecture/CompletedActions';
import CriticalPath from './architecture/CriticalPath';
import DomainExplainer from './architecture/DomainExplainer';
import MSPSummary from './architecture/MSPSummary';

// ─── Navigation ─────────────────────────────────────────────────────────────

function StickyNav({ activeSection }) {
  return (
    <nav className="sticky top-0 z-50 border-b border-slate-800/80 bg-slate-950/90 backdrop-blur-md print:hidden">
      <div className="mx-auto flex max-w-7xl items-center gap-1 overflow-x-auto px-4 py-2 sm:gap-2">
        {NAV_ITEMS.map(({ id, label }) => (
          <a
            key={id}
            href={`#${id}`}
            className={`shrink-0 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors sm:text-sm ${
              activeSection === id
                ? 'bg-slate-800 text-white'
                : 'text-slate-400 hover:bg-slate-800/60 hover:text-slate-200'
            }`}
          >
            {label}
          </a>
        ))}
        <div className="flex-1" />
        <a
          href="/ctu-dashboard/"
          className="shrink-0 rounded-lg border border-slate-700/50 bg-slate-800/40 px-3 py-1.5 text-xs font-medium text-slate-400 transition-colors hover:border-slate-600 hover:text-slate-200"
        >
          ← Audit Dashboard
        </a>
      </div>
    </nav>
  );
}

// ─── Active Section Tracker ─────────────────────────────────────────────────

function useActiveSection() {
  const [active, setActive] = useState('diagram');

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((e) => e.isIntersecting)
          .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
        if (visible.length > 0) setActive(visible[0].target.id);
      },
      { rootMargin: '-80px 0px -60% 0px', threshold: 0.1 },
    );

    NAV_ITEMS.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  return active;
}

// ─── Header ─────────────────────────────────────────────────────────────────

function Header() {
  return (
    <header className="border-b border-slate-800/50 bg-gradient-to-b from-htt/20 to-transparent pb-8 pt-10">
      <div className="mx-auto max-w-7xl px-4">
        {/* Logo area */}
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-htt text-sm font-black text-white">
            HTT
          </div>
          <span className="text-sm font-semibold tracking-wider text-slate-400">HTT BRANDS</span>
        </div>

        {/* Title */}
        <h1 className="mt-6 text-3xl font-extrabold tracking-tight text-white sm:text-4xl lg:text-5xl">
          Cross-Tenant Identity Architecture
        </h1>
        <p className="mt-2 text-base text-slate-400 sm:text-lg">
          Multi-Tenant Microsoft 365 Governance — Executive Overview
        </p>
        <p className="mt-1 text-sm text-slate-500">Updated April 13, 2026</p>
      </div>
    </header>
  );
}

// ─── Key Metrics Bar ────────────────────────────────────────────────────────

function MetricsBar() {
  return (
    <div className="border-b border-slate-800/50 bg-slate-900/50">
      <div className="mx-auto grid max-w-7xl grid-cols-2 gap-4 px-4 py-6 sm:grid-cols-3 lg:grid-cols-6">
        {METRICS.map(({ label, value, sub, color }) => (
          <div key={label} className="text-center">
            <p className={`text-2xl font-extrabold tracking-tight sm:text-3xl ${color}`}>{value}</p>
            <p className="mt-0.5 text-xs font-medium uppercase tracking-wider text-slate-400">{label}</p>
            {sub && <p className="mt-0.5 text-[10px] text-slate-500">{sub}</p>}
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── Footer ─────────────────────────────────────────────────────────────────

function Footer() {
  return (
    <footer className="border-t border-slate-800/50 py-8 text-center text-xs text-slate-600 print:hidden">
      <p>HTT Brands — Cross-Tenant Identity Architecture · Confidential</p>
      <p className="mt-1">
        Generated by{' '}
        <a href="/ctu-dashboard/" className="text-slate-500 underline hover:text-slate-400">
          CTU Dashboard
        </a>
      </p>
    </footer>
  );
}

// ─── Section Wrapper ────────────────────────────────────────────────────────

function Section({ id, children }) {
  return (
    <section id={id} className="scroll-mt-16 py-12 first:pt-8">
      {children}
    </section>
  );
}

// ─── Main Page ──────────────────────────────────────────────────────────────

export default function ArchitecturePage() {
  const activeSection = useActiveSection();

  return (
    <div className="min-h-screen bg-slate-950">
      <StickyNav activeSection={activeSection} />
      <Header />
      <MetricsBar />

      <main className="mx-auto max-w-7xl px-4">
        <Section id="diagram">
          <HubSpokeDiagram />
        </Section>

        <Section id="progress">
          <PhaseTracker />
        </Section>

        <Section id="completed">
          <CompletedActions />
        </Section>

        <Section id="next-steps">
          <CriticalPath />
        </Section>

        <Section id="domains">
          <DomainExplainer />
        </Section>

        <Section id="msp">
          <MSPSummary />
        </Section>
      </main>

      <Footer />
    </div>
  );
}
